{{- range $index, $network := .Values.networks }}
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: marlowe-runner-{{ $network }}
  namespace: marlowe-production
spec:
  components:
    - name: marlowe-runner-{{ $network }}
      properties:
        image: p3terx/darkhttpd
        args:
          - /client-www
          - --port
          - "8080"
        imagePullPolicy: Always
        ports:
          - expose: true
            port: 8080
            protocol: TCP
      traits:
        - properties:
            replicas: 1
          type: scaler
        - properties:
            domains:
              - {{ $network }}.runner.marlowe.iohk.io
            rules:
              - port: 8080
          type: https-route
        - type: init-container
          properties:
            name: load-runner-client
            image: ghcr.io/input-output-hk/marlowe-runner:{{ $.Values.images.productionTag }}
            args:
              - -c
              - |
                  root="$(dirname $(readlink -f /profile/index.html))"
                  cp -a $root/* /share/marlowe-runner/static
                  cat > /share/marlowe-runner/static/config.json <<EOF
                  {
                    "marloweWebServerUrl": "https://marlowe-runtime-{{ $network }}-web.scdev.aws.iohkdev.io",
                    "develMode": false
                  }
                  EOF
            mountName: client-www
            initMountPath: /share/marlowe-runner/static
            appMountPath: /client-www
      type: webservice
  policies:
    - name: marlowe-runner-staging
      properties:
        clusters:
          - local
        namespace: marlowe-staging
      type: topology

    - name: marlowe-runner
      properties:
        clusters:
          - local
        namespace: marlowe-production
      type: topology

    - name: staging-override
      type: override
      properties:
        components:
          - name: marlowe-runner-{{ $network }}-staging
            properties:
              image: p3terx/darkhttpd
              args:
                - /client-www
                - --port
                - "8080"
              imagePullPolicy: Always
              ports:
                - expose: true
                  port: 8080
                  protocol: TCP
            traits:
              - properties:
                  replicas: 1
                type: scaler
              - properties:
                  domains:
                    - runner-{{ $network }}.scdev.aws.iohkdev.io
                  rules:
                    - port: 8080
                type: https-route
              - type: init-container
                properties:
                  name: load-runner-client
                  image: ghcr.io/input-output-hk/marlowe-runner:{{ $.Values.images.stagingTag }}
                  args:
                    - -c
                    - |
                        root="$(dirname $(readlink -f /profile/index.html))"
                        cp -a $root/* /share/marlowe-runner/static
                        cat > /share/marlowe-runner/static/config.json <<EOF
                        {
                          "marloweWebServerUrl": "https://marlowe-runtime-{{ $network }}-web.scdev.aws.iohkdev.io",
                          "develMode": false
                        }
                        EOF
                  mountName: client-www
                  initMountPath: /share/marlowe-runner/static
                  appMountPath: /client-www
            type: webservice
  workflow:
    mode:
      steps: DAG
    steps:
      - meta:
          alias: Push staging image
        name: push-image-staging
        type: build-nix-image
        properties:
          image: ghcr.io/input-output-hk/marlowe-runner:{{ $.Values.images.stagingTag }}
          requests:
            ephemeralStorage: 25Gi
          includedFlakeURIs:
            - "github:input-output-hk/marlowe-runner?ref={{ $.Values.images.stagingTag }}#marlowe-runner"
      - meta:
          alias: Push image
        name: push-image
        type: build-nix-image
        properties:
          image: ghcr.io/input-output-hk/marlowe-runner:{{ $.Values.images.productionTag }}
          requests:
            ephemeralStorage: 25Gi
          includedFlakeURIs:
            - "github:input-output-hk/marlowe-runner?ref={{ $.Values.images.productionTag }}#marlowe-runner"
      - type: deploy
        meta:
          alias: Deploy marlowe-runner
        dependsOn:
          - push-image
        name: marlowe-runner
        properties:
          policies:
            - marlowe-runner
      - type: deploy
        meta:
          alias: Deploy marlowe-runner to staging
        dependsOn:
          - push-image-staging
        name: marlowe-runner-staging
        properties:
          policies:
            - marlowe-runner-staging
            - staging-override
{{- end }}
